<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beli</name>
   <tag></tag>
   <elementGuidId>5745516b-f569-4182-a0ee-49381a8f10e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.c-btn--spinner__icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vm-vp-data-plan-prepaid']/div/div[2]/main/div/article/div[2]/div[2]/ul/li[3]/div/div[2]/div/div[2]/button/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;vm-vp-data-plan-prepaid&quot;)/div[@class=&quot;u-bg--sand&quot;]/div[@class=&quot;o-container o-container--responsive&quot;]/main[1]/div[@class=&quot;mx-auto&quot;]/article[@class=&quot;bg-white mb-xl border-thin border-ui-dark&quot;]/div[@class=&quot;text-base&quot;]/div[@class=&quot;bg-ui-light pb-xl&quot;]/ul[@class=&quot;flex flex-wrap mx-xl qa-products&quot;]/li[@class=&quot;lg_w-2_12 md_w-3_12 sm_w-6_12 w-full p-none&quot;]/div[@class=&quot;relative qa-package h-full pt-xl qa-product z-20&quot;]/div[@class=&quot;border-thin rounded border-ui-dark py-xl px-2xl bg-white mx-md mb-lg hover_bg-ui-white relative h-full flex flex-col justify-between qa-package-item cursor-pointer is-active z-modal border-crimson&quot;]/div[@class=&quot;border-thin rounded border-ui-dark absolute py-xl px-2xl bg-white flex items-center left-0 mx-md item qa-package-item-dropdown&quot;]/div[@class=&quot;flex-none&quot;]/button[@class=&quot;c-btn c-btn--large c-btn--default c-btn--red c-btn--spinner&quot;]/i[@class=&quot;c-btn--spinner__icon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-btn--spinner__icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vm-vp-data-plan-prepaid&quot;)/div[@class=&quot;u-bg--sand&quot;]/div[@class=&quot;o-container o-container--responsive&quot;]/main[1]/div[@class=&quot;mx-auto&quot;]/article[@class=&quot;bg-white mb-xl border-thin border-ui-dark&quot;]/div[@class=&quot;text-base&quot;]/div[@class=&quot;bg-ui-light pb-xl&quot;]/ul[@class=&quot;flex flex-wrap mx-xl qa-products&quot;]/li[@class=&quot;lg_w-2_12 md_w-3_12 sm_w-6_12 w-full p-none&quot;]/div[@class=&quot;relative qa-package h-full pt-xl qa-product z-20&quot;]/div[@class=&quot;border-thin rounded border-ui-dark py-xl px-2xl bg-white mx-md mb-lg hover_bg-ui-white relative h-full flex flex-col justify-between qa-package-item cursor-pointer is-active z-modal border-crimson&quot;]/div[@class=&quot;border-thin rounded border-ui-dark absolute py-xl px-2xl bg-white flex items-center left-0 mx-md item qa-package-item-dropdown&quot;]/div[@class=&quot;flex-none&quot;]/button[@class=&quot;c-btn c-btn--large c-btn--default c-btn--red c-btn--spinner&quot;]/i[@class=&quot;c-btn--spinner__icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vm-vp-data-plan-prepaid']/div/div[2]/main/div/article/div[2]/div[2]/ul/li[3]/div/div[2]/div/div[2]/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
   </webElementXpaths>
</WebElementEntity>
