<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Roaming_markv-overlay</name>
   <tag></tag>
   <elementGuidId>32199f95-bc06-45ec-b2d1-fc0bbef9a4ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.markv-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vm-vp-data-plan-prepaid']/div/div[2]/main/div/article/div[2]/div[2]/ul/li[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>markv-overlay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vm-vp-data-plan-prepaid&quot;)/div[@class=&quot;u-bg--sand&quot;]/div[@class=&quot;o-container o-container--responsive&quot;]/main[1]/div[@class=&quot;mx-auto&quot;]/article[@class=&quot;bg-white mb-xl border-thin border-ui-dark&quot;]/div[@class=&quot;text-base&quot;]/div[@class=&quot;bg-ui-light pb-xl&quot;]/ul[@class=&quot;flex flex-wrap mx-xl qa-products&quot;]/li[@class=&quot;lg_w-2_12 md_w-3_12 sm_w-6_12 w-full p-none&quot;]/div[@class=&quot;relative qa-package h-full pt-xl qa-product z-20&quot;]/div[@class=&quot;markv-overlay&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vm-vp-data-plan-prepaid']/div/div[2]/main/div/article/div[2]/div[2]/ul/li[3]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roaming'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reguler'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='telkomsel'])[1]/preceding::div[172]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
