<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomer Telepon</name>
   <tag></tag>
   <elementGuidId>e1ac1a3d-6f13-47a4-b74c-aaa69a3cf396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.c-inp.c-inp--large.font-bold.qa-phone-number-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vm-vp-data-plan-prepaid']/div/div[2]/main/div/article/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Telepon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inp c-inp--large font-bold qa-phone-number-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vm-vp-data-plan-prepaid&quot;)/div[@class=&quot;u-bg--sand&quot;]/div[@class=&quot;o-container o-container--responsive&quot;]/main[1]/div[@class=&quot;mx-auto&quot;]/article[@class=&quot;bg-white mb-xl border-thin border-ui-dark&quot;]/div[@class=&quot;m-2xl&quot;]/div[@class=&quot;relative flex items-center&quot;]/input[@class=&quot;c-inp c-inp--large font-bold qa-phone-number-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vm-vp-data-plan-prepaid']/div/div[2]/main/div/article/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
