<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment Category</name>
   <tag></tag>
   <elementGuidId>fa4b5744-2f98-4f88-8d26-2118fe9fb1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#virtual_account</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='virtual_account']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment-category</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>virtual_account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-radio-button__input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>virtual_account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vm__payment-checkout&quot;)/div[@class=&quot;bl-container pt-24 pb-24&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item vp-checkout__sidebar vp-checkout__sidebar--left mr-24&quot;]/fragment-loader[@class=&quot;vp-checkout__adjust-payment qa-checkout__adjust-payment&quot;]/div[@class=&quot;tuku&quot;]/div[1]/section[1]/div[1]/div[@class=&quot;mb-20 bl-card bl-card--outlined&quot;]/div[3]/div[@class=&quot;bl-payment-category&quot;]/label[@class=&quot;bl-payment-category__label&quot;]/div[@class=&quot;bl-flex-container p-20&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-radio-button&quot;]/input[@id=&quot;virtual_account&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='virtual_account']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vm__payment-checkout']/div/div/div/fragment-loader/div/div/section/div/div/div[3]/div/label/div/div/label/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label/div/div/label/input</value>
   </webElementXpaths>
</WebElementEntity>
